FROM python:alpine

RUN apk add --no-cache gcc musl-dev linux-headers pcre-dev

RUN pip install --no-cache-dir Flask
RUN pip install --no-cache-dir uwsgi

WORKDIR /usr/app

COPY ./app.py ./app.py
COPY ./uwsgi.ini ./uwsgi.ini

ENTRYPOINT ["uwsgi", "/usr/app/uwsgi.ini"] 
